### ISSUE TITLE
良くないタグ付け

### ISSUE THREAD

**Issue by nasa9084** [manzyun/personal_history_made_by_html5#2]
``` html
<div class="clear">
<hr>
</div>
```

上記部分はちょっとどうなのかなと。cssを見るとhrはdisplay:none;されているようですし、、、

**Comment by manzyun** [comment]
現状のデザイン上（というよりCSSの無知）の都合です。
できれば無くしたいタグではあります。

**Comment by manzyun** [comment]
このコミットで解決しました。
8de296f9f7301bb7ac0967a30affc2281bee6e18
