### ISSUE TITLE
body直下のarticle

### ISSUE THREAD

**Issue by nasa9084** [manzyun/personal_history_made_by_html5#3]
body直下のarticleはどういった意味があるのでしょうか。

**Comment by manzyun** [comment]
「一つの履歴書」という意味合いで付けてますが、それはbodyが既に賄っているのか……。ちょっと考え直してみます。

**Comment by manzyun** [comment]
このコミットで解決しました。
b988bdf9a1840bacf24b9baa45c7eed24bbcdfa5
