### ISSUE TITLE
履歴書＝resume？

### ISSUE THREAD

**Issue by chuck0523** [manzyun/personal_history_made_by_html5#4]
履歴書を表す英語は、resumeのほうがポピュラーな気がします。
http://eow.alc.co.jp/search?q=%E5%B1%A5%E6%AD%B4%E6%9B%B8

**Comment by chuck0523** [comment]
↑という前提にたって、READMEの修正プルリクを出させていただきました〜
https://github.com/manzyun/personal_history_made_by_html5/pull/5

**Comment by manzyun** [comment]
確かにResumeの方がポピュラーだよなあとは思っておりました。
ありがとうございます！
